<a href="https://colab.research.google.com/github/conglapgit45/KNN_and_Kmean/blob/main/K_Mean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [11]:
# Create data
Feature_01 = np.array([2.0, 3.0, 3.5, 8.0, 8.5, 9.0, 1.0, 1.5])
Feature_02 = np.array([3.0, 3.5, 3.0, 8.0, 8.5, 8.0, 2.0, 2.5])
Feature_03 = np.array([1.5, 2.0, 2.5, 7.5, 8.0, 8.5, 1.0, 1.5])

X = np.array([Feature_01, Feature_02, Feature_03]).T
print(X)

[[2.  3.  1.5]
 [3.  3.5 2. ]
 [3.5 3.  2.5]
 [8.  8.  7.5]
 [8.5 8.5 8. ]
 [9.  8.  8.5]
 [1.  2.  1. ]
 [1.5 2.5 1.5]]


In [59]:
# set number of cluster and select centroids
k = 2
C1 = X[0]
C2 = X[3]
print(C1)
print(C2)

Centroids = np.array([C1, C2]).T
print(Centroids)

[2.  3.  1.5]
[8.  8.  7.5]
[[2.  8. ]
 [3.  8. ]
 [1.5 7.5]]


In [60]:
# compute distances
distances = np.sqrt(np.sum(np.power(X[:, :, np.newaxis] - Centroids, 2), axis=1))
print(distances)

[[ 0.          9.8488578 ]
 [ 1.22474487  8.6890736 ]
 [ 1.80277564  8.38152731]
 [ 9.8488578   0.        ]
 [10.71214264  0.8660254 ]
 [11.09053651  1.41421356]
 [ 1.5        11.28051417]
 [ 0.70710678 10.41633333]]


In [61]:
# assign cluster
clusters = np.argmin(distances, axis=1)
print(clusters)

[0 0 0 1 1 1 0 0]


In [57]:
# new centroids
new_centroids = np.array([X[clusters == i].mean(axis=0) for i in range(k)])
print(new_centroids)

[[5.07142857 5.21428571 4.5       ]
 [1.         2.         1.        ]]
